// db/seed/excursions.ts
import { getServiceRoleSupabase } from "./_supabase";

type Row = {
  slug: string;
  title: string;
  short_description: string;
  image_url: string;
  price_from_usd: number;
  duration_min: number;
  duration_max?: number;
  type: "cruise_day" | "multi_day" | "both";
  viator_slug: string;
  viator_attraction_id: string;
  viator_base_level: "San-Juan" | "Puerto-Rico" | "Vieques" | "Fajardo";
  category: string;
  is_hero?: boolean;
  sort_order: number;
};

// Image URL helper — picks a stable Unsplash photo for the category.
const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=70&fm=webp`;

const cruiseDay: Row[] = [
  { slug: "old-san-juan-walking", title: "Old San Juan Walking Tour", short_description: "Cobblestone streets, UNESCO history, and 500 years of stories.", image_url: img("photo-1565066019713-2886b345a96c"), price_from_usd: 45, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", is_hero: true, sort_order: 1 },
  { slug: "el-morro-fort-tour", title: "Castillo San Felipe del Morro Tour", short_description: "The 16th-century clifftop Spanish fortress guarding San Juan Bay.", image_url: img("photo-1589402278102-d3a969a78713"), price_from_usd: 10, duration_min: 120, type: "cruise_day", viator_slug: "Castillo-San-Felipe-del-Morro", viator_attraction_id: "d903-a3885", viator_base_level: "San-Juan", category: "history", is_hero: true, sort_order: 2 },
  { slug: "casa-bacardi-distillery", title: "Casa Bacardí Distillery Tour", short_description: "The world's largest premium rum distillery, with a signature cocktail.", image_url: img("photo-1574713600544-ca13b5d573d5"), price_from_usd: 33, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", is_hero: true, sort_order: 3 },
  { slug: "el-yunque-half-day", title: "El Yunque Rainforest Half-Day Tour", short_description: "Tropical rainforest with waterfalls, lookouts, and lush trails.", image_url: img("photo-1561271484-3a69b8e31344"), price_from_usd: 60, duration_min: 240, duration_max: 300, type: "cruise_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "nature", is_hero: true, sort_order: 4 },
  { slug: "flavors-san-juan-food-tour", title: "Flavors of San Juan Food Tour", short_description: "Mofongo, lechón, alcapurrias, and mojito across nine stops.", image_url: img("photo-1504674900247-0877df9cc836"), price_from_usd: 99, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", is_hero: true, sort_order: 5 },
  { slug: "el-morro-cristobal-combo", title: "El Morro + San Cristóbal Combo Walking Tour", short_description: "Both UNESCO forts in a single half-day pass.", image_url: img("photo-1665980531889-04e530633bec"), price_from_usd: 54, duration_min: 180, type: "cruise_day", viator_slug: "Castillo-San-Felipe-del-Morro", viator_attraction_id: "d903-a3885", viator_base_level: "San-Juan", category: "history", sort_order: 6 },
  { slug: "bacardi-mixology-class", title: "Casa Bacardí Rum Mixology Class", short_description: "Hands-on cocktail class with a master mixologist.", image_url: img("photo-1570448690239-4050e1eb92f3"), price_from_usd: 60, duration_min: 120, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", sort_order: 7 },
  { slug: "mofongo-mojito-class", title: "Mofongo & Mojito Cooking Class", short_description: "Pound your own mofongo and muddle your own mojito.", image_url: img("photo-1514362545857-3bc16c4c7d1b"), price_from_usd: 89, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 8 },
  { slug: "el-yunque-luquillo", title: "El Yunque + Luquillo Beach Half-Day", short_description: "Hike to a waterfall, then cool off at Luquillo Beach.", image_url: img("photo-1507525428034-b723cf961d3e"), price_from_usd: 50, duration_min: 300, duration_max: 360, type: "cruise_day", viator_slug: "Luquillo-Beach", viator_attraction_id: "d903-a10255", viator_base_level: "San-Juan", category: "nature", sort_order: 9 },
  { slug: "osj-rum-salsa-class", title: "Old San Juan Rum & Salsa Class", short_description: "Two rum cocktails and basic salsa steps in three breezy hours.", image_url: img("photo-1555489401-79c274997434"), price_from_usd: 79, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 10 },
  { slug: "escambron-snorkel", title: "Escambrón Beach Snorkel Tour", short_description: "Protected reef teeming with sea turtles, minutes from the pier.", image_url: img("photo-1582273417870-183e69b360e7"), price_from_usd: 45, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "water", sort_order: 11 },
  { slug: "condado-clear-kayak", title: "Clear-Kayak Tour of Condado Lagoon", short_description: "Paddle a see-through kayak across a calm urban lagoon.", image_url: img("photo-1612103183244-7598b792bb05"), price_from_usd: 65, duration_min: 90, duration_max: 120, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "water", sort_order: 12 },
  { slug: "san-juan-bay-catamaran", title: "San Juan Bay Catamaran Snorkel & Sail", short_description: "Half-day sail with snorkel stop and skyline views.", image_url: img("photo-1629908513781-1857f7ec2c8a"), price_from_usd: 95, duration_min: 180, duration_max: 240, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 13 },
  { slug: "osj-self-audio-tour", title: "Old San Juan Self-Guided Audio Tour", short_description: "App-based walking tour, perfect for tight cruise schedules.", image_url: img("photo-1565066021936-08655d8ec3ab"), price_from_usd: 13, duration_min: 60, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", sort_order: 14 },
  { slug: "osj-ghost-walk", title: "Old San Juan Ghost Walk", short_description: "Lantern-lit evening tour through haunted plazas.", image_url: img("photo-1705496464785-4a7dd68e870e"), price_from_usd: 35, duration_min: 120, duration_max: 150, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", sort_order: 15 },
  { slug: "bacardi-osj-combo", title: "Bacardí + Old San Juan Combo", short_description: "Rum distillery + walking tour in one half day.", image_url: img("photo-1608232385022-8ba61bec6c59"), price_from_usd: 89, duration_min: 300, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", sort_order: 16 },
  { slug: "san-juan-harbor-cruise", title: "San Juan Harbor Sightseeing Cruise", short_description: "Narrated 90-minute harbor cruise with El Morro views.", image_url: img("photo-1658296628319-18f20d8525a4"), price_from_usd: 35, duration_min: 90, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 17 },
  { slug: "osj-sip-stroll", title: "Old San Juan Sip & Stroll Mojito Tour", short_description: "Three bars, three mojitos, one walking guide.", image_url: img("photo-1514362545857-3bc16c4c7d1b"), price_from_usd: 69, duration_min: 150, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 18 },
  { slug: "osj-sunset-harbor", title: "Old San Juan Sunset Harbor Tour", short_description: "Late-afternoon harbor cruise timed for golden hour.", image_url: img("photo-1495954484750-af469f2f9be5"), price_from_usd: 59, duration_min: 120, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 19 },
  { slug: "san-juan-jet-ski", title: "Jet Ski Tour of San Juan Bay", short_description: "Buzz across the bay with El Morro as your backdrop.", image_url: img("photo-1554132267-d06483b00adc"), price_from_usd: 169, duration_min: 60, duration_max: 120, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 20 },
];

const multiDay: Row[] = [
  { slug: "vieques-bio-bay-kayak", title: "Vieques Bio Bay (Mosquito Bay) Kayak", short_description: "Every paddle stroke ignites blue plankton beneath your kayak.", image_url: img("photo-1552957091-7d7113198882"), price_from_usd: 65, duration_min: 90, duration_max: 120, type: "multi_day", viator_slug: "Bioluminescent-Bay", viator_attraction_id: "d22812-a22596", viator_base_level: "Vieques", category: "water", is_hero: true, sort_order: 101 },
  { slug: "culebra-flamenco-catamaran", title: "Culebra & Flamenco Beach Catamaran Day Trip", short_description: "Snorkel Carlos Rosario reef and beach on world-ranked Flamenco Beach.", image_url: img("photo-1507525428034-b723cf961d3e"), price_from_usd: 185, duration_min: 480, duration_max: 600, type: "multi_day", viator_slug: "Culebra-Island", viator_attraction_id: "d36-a19414", viator_base_level: "Puerto-Rico", category: "water", is_hero: true, sort_order: 102 },
  { slug: "el-yunque-full-day", title: "El Yunque Full-Day Rainforest & Waterfalls", short_description: "La Coca and Juan Diego falls, plus a Luquillo Beach finale.", image_url: img("photo-1561271484-3a69b8e31344"), price_from_usd: 80, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "nature", is_hero: true, sort_order: 103 },
  { slug: "toro-verde-beast", title: "Toro Verde 'The Beast' Zipline", short_description: "Nearly a mile across a mountain valley at 60 mph.", image_url: img("photo-1648853070657-6d58398bee93"), price_from_usd: 67, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", is_hero: true, sort_order: 104 },
  { slug: "fajardo-bio-bay-kayak", title: "Fajardo Laguna Grande Bio Bay Kayak", short_description: "The most-accessible bioluminescent lagoon, done from San Juan in one evening.", image_url: img("photo-1536441918530-c3bae05caf69"), price_from_usd: 69, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", is_hero: true, sort_order: 105 },
  { slug: "culebra-ferry-turtle", title: "Culebra Island Ferry + Turtle Swim", short_description: "Ferry, sea turtles in Luis Peña Reserve, plus Flamenco Beach.", image_url: img("photo-1591025207163-942350e47db2"), price_from_usd: 175, duration_min: 600, duration_max: 720, type: "multi_day", viator_slug: "Flamenco-Beach-Playa-Flamenco", viator_attraction_id: "d903-a15793", viator_base_level: "San-Juan", category: "water", sort_order: 106 },
  { slug: "el-yunque-waterslide", title: "El Yunque Waterslide & Cliff-Jumping", short_description: "Off-the-beaten-path waterfalls with 20-foot cliff jumps.", image_url: img("photo-1597627094703-2a8af9caa749"), price_from_usd: 85, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "adventure", sort_order: 107 },
  { slug: "fajardo-catamaran-icacos", title: "Fajardo Catamaran Snorkel & Sunset Sail", short_description: "All-day or sunset catamaran to Icacos and Palomino.", image_url: img("photo-1629908513781-1857f7ec2c8a"), price_from_usd: 119, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", sort_order: 108 },
  { slug: "toro-verde-monster", title: "Toro Verde 'The Monster' Zipline", short_description: "World's longest zipline — 1.5 miles superman-style.", image_url: img("photo-1649017610908-c0ff38eb29b8"), price_from_usd: 125, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", sort_order: 109 },
  { slug: "rio-camuy-caves", title: "Río Camuy Cave Park & Arecibo Day Trip", short_description: "Third-longest underground river system in the world.", image_url: img("photo-1725780632003-894557a203f7"), price_from_usd: 99, duration_min: 480, duration_max: 540, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "nature", sort_order: 110 },
  { slug: "cueva-ventana", title: "Cueva Ventana 'Window Cave' & Waterfall", short_description: "Clifftop cave with a window view over the Río Grande de Arecibo.", image_url: img("photo-1613069552490-dbb6cb30cd90"), price_from_usd: 89, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "nature", sort_order: 111 },
  { slug: "charco-azul", title: "Charco Azul Cave, River & Waterfall", short_description: "Arenales caves, turquoise swimming hole, hidden waterfalls.", image_url: img("photo-1536625637853-ec02b2b4edbd"), price_from_usd: 75, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "adventure", sort_order: 112 },
  { slug: "hacienda-campo-rico-atv", title: "Hacienda Campo Rico ATV Adventure", short_description: "Drive an ATV across 2,300 acres of mangroves and lookouts.", image_url: img("photo-1675428604186-a165487f857c"), price_from_usd: 149, duration_min: 180, duration_max: 240, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", sort_order: 113 },
  { slug: "carabali-horseback", title: "Carabalí Rainforest Beach Horseback Ride", short_description: "Paso Fino horses along the Mameyes River and Atlantic beaches.", image_url: img("photo-1598711033236-3e0b403a14e8"), price_from_usd: 95, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "adventure", sort_order: 114 },
  { slug: "icacos-catamaran-picnic", title: "Icacos Deserted Island Catamaran & Picnic", short_description: "All-day catamaran to a deserted cay with lunch and drinks.", image_url: img("photo-1582967788606-a171c1080cb0"), price_from_usd: 139, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", sort_order: 115 },
  { slug: "la-parguera-bio-bay", title: "La Parguera Bio Bay Boat & Swim", short_description: "PR's only swimmable bio bay — splash through bioluminescent water.", image_url: img("photo-1579332550177-31a901024747"), price_from_usd: 55, duration_min: 480, duration_max: 600, type: "multi_day", viator_slug: "Bioluminescent-Bay", viator_attraction_id: "d22812-a22596", viator_base_level: "Vieques", category: "water", sort_order: 116 },
  { slug: "three-in-one-day", title: "Old San Juan, El Yunque & Beach (3-in-1)", short_description: "Old San Juan, El Yunque waterfalls, and Luquillo Beach in one day.", image_url: img("photo-1565066019713-2886b345a96c"), price_from_usd: 65, duration_min: 480, duration_max: 540, type: "multi_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "combo", sort_order: 117 },
  { slug: "vieques-bio-bay-from-sj", title: "Vieques Bio Bay Day Trip from San Juan", short_description: "Same-day round-trip ferry + van combo for the brightest bio bay.", image_url: img("photo-1552957091-7d7113198882"), price_from_usd: 230, duration_min: 840, duration_max: 960, type: "multi_day", viator_slug: "Vieques-Island", viator_attraction_id: "d36-a19410", viator_base_level: "Puerto-Rico", category: "water", sort_order: 118 },
  { slug: "rio-grande-loiza-kayak", title: "Río Grande de Loíza Kayak & Mangrove Tour", short_description: "Quiet paddle through Loíza's Afro-Caribbean mangrove estuary.", image_url: img("photo-1612103183244-7598b792bb05"), price_from_usd: 65, duration_min: 240, duration_max: 300, type: "multi_day", viator_slug: "Luquillo-Beach", viator_attraction_id: "d903-a10255", viator_base_level: "San-Juan", category: "water", sort_order: 119 },
  { slug: "bacardi-sunset-sail", title: "Bacardí Historic Sunset Boat Tour", short_description: "Romantic evening sail with cocktails timed to sunset over El Morro.", image_url: img("photo-1570191668385-84b70602b249"), price_from_usd: 89, duration_min: 120, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 120 },
];

// ──────────────────────────────────────────────────────────────────────────────
// NEW BATCH — 30 additional bookable Puerto Rico excursions (sort_order 201+)
// All Viator links confirmed via search; attraction IDs that couldn't be
// independently verified fall back to the head URL anchor (d36-a19408).
// ──────────────────────────────────────────────────────────────────────────────

const extraCruiseDay: Row[] = [
  {
    slug: "osj-loiza-santurce-art",
    title: "Old San Juan, Loíza & Santurce Street-Art Tour",
    short_description: "Vibrant murals, Afro-Caribbean culture, and Santurce's booming arts scene in one half-day.",
    image_url: img("photo-1593073862407-a3ce22748763"),
    price_from_usd: 79,
    duration_min: 240,
    duration_max: 300,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-333075P1",
    viator_base_level: "San-Juan",
    category: "culture",
    sort_order: 201,
  },
  {
    slug: "san-juan-parasailing",
    title: "San Juan Bay Parasailing Adventure",
    short_description: "800 feet above the turquoise bay — breathtaking views of El Morro and the coastline.",
    image_url: img("photo-1551698618-1dfe5d97d256"),
    price_from_usd: 75,
    duration_min: 60,
    duration_max: 90,
    type: "cruise_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-a22255",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 202,
  },
  {
    slug: "san-juan-sup-paddleboard",
    title: "Stand-Up Paddleboard Tour of Condado Lagoon",
    short_description: "Guided SUP session on calm urban lagoon waters — great for all skill levels.",
    image_url: img("photo-1544551763-46a013bb70d5"),
    price_from_usd: 55,
    duration_min: 90,
    duration_max: 120,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-a2460",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 203,
  },
  {
    slug: "san-juan-helicopter-25min",
    title: "25-Minute Helicopter Tour Over Puerto Rico",
    short_description: "Soar over El Morro, the Karst Forest, and the San Juan coastline from above.",
    image_url: img("photo-1464037866556-6812c9d1c72e"),
    price_from_usd: 199,
    duration_min: 25,
    duration_max: 45,
    type: "cruise_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-452098P3",
    viator_base_level: "San-Juan",
    category: "adventure",
    sort_order: 204,
  },
  {
    slug: "deep-sea-fishing-san-juan",
    title: "Deep-Sea Fishing Charter — San Juan",
    short_description: "Hunt blue marlin, wahoo, and mahi-mahi aboard a private sport-fishing yacht.",
    image_url: img("photo-1545816250-e31ee02e78d6"),
    price_from_usd: 195,
    duration_min: 240,
    duration_max: 480,
    type: "cruise_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-4170FISH",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 205,
  },
  {
    slug: "tarpon-light-tackle-sj",
    title: "Light-Tackle Tarpon Fishing — Laguna San José",
    short_description: "San Juan is world-famous for tarpon. Cast light tackle with a local captain.",
    image_url: img("photo-1493551060832-5a2b72c7b92b"),
    price_from_usd: 150,
    duration_min: 240,
    duration_max: 300,
    type: "cruise_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-4170P14",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 206,
  },
  {
    slug: "pinones-food-crawl",
    title: "Piñones Afro-Caribbean Food Crawl",
    short_description: "Alcapurrias, bacalaítos, and chillo frito at open-air kiosks along the coastal road.",
    image_url: img("photo-1504674900247-0877df9cc836"),
    price_from_usd: 65,
    duration_min: 180,
    duration_max: 240,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-a2460",
    viator_base_level: "San-Juan",
    category: "culinary",
    sort_order: 207,
  },
  {
    slug: "osj-evening-pub-crawl",
    title: "Old San Juan Evening Pub Crawl",
    short_description: "Three iconic OSJ bars, two free welcome drinks, and a dancing finale.",
    image_url: img("photo-1514362545857-3bc16c4c7d1b"),
    price_from_usd: 49,
    duration_min: 150,
    duration_max: 210,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-a2460",
    viator_base_level: "San-Juan",
    category: "culinary",
    sort_order: 208,
  },
  {
    slug: "san-juan-led-night-kayak",
    title: "LED Night Kayak on Condado Lagoon",
    short_description: "Glow-lit kayaks and paddleboards glide through the dark lagoon at sunset.",
    image_url: img("photo-1536441918530-c3bae05caf69"),
    price_from_usd: 69,
    duration_min: 90,
    duration_max: 120,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-107272P1",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 209,
  },
  {
    slug: "salsa-congress-class-sj",
    title: "Puerto Rico Salsa Dance Class — San Juan",
    short_description: "Two-hour lesson in authentic Puerto Rican on-2 salsa with a professional instructor.",
    image_url: img("photo-1555489401-79c274997434"),
    price_from_usd: 59,
    duration_min: 120,
    type: "cruise_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-a2460",
    viator_base_level: "San-Juan",
    category: "culture",
    sort_order: 210,
  },
];

const extraMultiDay: Row[] = [
  {
    slug: "cabo-rojo-lighthouse-biobay",
    title: "Cabo Rojo Lighthouse, Playa Sucia & La Parguera Bio Bay",
    short_description: "Cliff lighthouse, pink salt flats, snorkeling, then bioluminescent swim at La Parguera.",
    image_url: img("photo-1507525428034-b723cf961d3e"),
    price_from_usd: 139,
    duration_min: 660,
    duration_max: 780,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d903-135749P9",
    viator_base_level: "Puerto-Rico",
    category: "nature",
    sort_order: 301,
  },
  {
    slug: "ponce-historical-cultural",
    title: "Ponce Historical & Cultural Day Trip from San Juan",
    short_description: "Parque de Bombas, Ponce Art Museum, Serallès Castle — Puerto Rico's second city in full.",
    image_url: img("photo-1565066019713-2886b345a96c"),
    price_from_usd: 99,
    duration_min: 540,
    duration_max: 600,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d903-4170PONCE",
    viator_base_level: "Puerto-Rico",
    category: "history",
    sort_order: 302,
  },
  {
    slug: "caja-de-muertos-catamaran",
    title: "Caja de Muertos Island Catamaran Day Trip",
    short_description: "All-day sail to a deserted island: snorkeling reefs, hiking, lunch, and open bar.",
    image_url: img("photo-1629908513781-1857f7ec2c8a"),
    price_from_usd: 125,
    duration_min: 480,
    duration_max: 600,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-66882P1",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 303,
  },
  {
    slug: "guanica-dry-forest-snorkel",
    title: "Guánica Dry Forest & Snorkel Day Trip from San Juan",
    short_description: "Hike UNESCO-listed tropical dry forest, then snorkel pristine Caribbean reefs.",
    image_url: img("photo-1587060001248-83f7ecfad62b"),
    price_from_usd: 119,
    duration_min: 600,
    duration_max: 660,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d27489-35486P8",
    viator_base_level: "Puerto-Rico",
    category: "nature",
    sort_order: 304,
  },
  {
    slug: "ponce-southwest-full-day",
    title: "Southwest Puerto Rico: Ponce, Guánica & Cabo Rojo",
    short_description: "Three iconic southern destinations — neoclassical architecture, dry forest, and salt flats.",
    image_url: img("photo-1499424769867-03de11e2d3c3"),
    price_from_usd: 129,
    duration_min: 600,
    duration_max: 720,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "history",
    sort_order: 305,
  },
  {
    slug: "cueva-del-indio-charco-azul",
    title: "Cueva del Indio & Charco Azul Full-Day Adventure",
    short_description: "Seaside Taíno petroglyphs cave, then a turquoise waterfall swimming hole.",
    image_url: img("photo-1613069552490-dbb6cb30cd90"),
    price_from_usd: 110,
    duration_min: 480,
    duration_max: 540,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d34207-322734P11",
    viator_base_level: "Puerto-Rico",
    category: "nature",
    sort_order: 306,
  },
  {
    slug: "arecibo-observatory-mar-chiquita",
    title: "Arecibo Observatory & Mar Chiquita Natural Pool",
    short_description: "Visit the world's second-largest radio telescope, then swim in a natural ocean pool.",
    image_url: img("photo-1519681393784-d120267933ba"),
    price_from_usd: 115,
    duration_min: 540,
    duration_max: 600,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d34207-108398P9",
    viator_base_level: "Puerto-Rico",
    category: "nature",
    sort_order: 307,
  },
  {
    slug: "arecibo-utv-cueva-del-indio",
    title: "Arecibo UTV Ride to Cueva del Indio",
    short_description: "Off-road UTV adventure to a dramatic coastal cave with Taíno rock art.",
    image_url: img("photo-1675428604186-a165487f857c"),
    price_from_usd: 129,
    duration_min: 420,
    duration_max: 480,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-57869P14",
    viator_base_level: "Puerto-Rico",
    category: "adventure",
    sort_order: 308,
  },
  {
    slug: "loiza-african-heritage-tour",
    title: "Loíza & Piñones Afro–Puerto Rican Heritage Tour",
    short_description: "Bomba drums, Vejigante mask shops, African-root cuisine, and a hidden beach.",
    image_url: img("photo-1583510383754-35fc1d1eb598"),
    price_from_usd: 89,
    duration_min: 360,
    duration_max: 420,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d903-14030P25",
    viator_base_level: "Puerto-Rico",
    category: "culture",
    sort_order: 309,
  },
  {
    slug: "osj-loiza-african-town",
    title: "Old San Juan & Loíza African Town Day Tour",
    short_description: "From colonial fortresses to Afro-Caribbean mask-makers — Puerto Rico's dual heritage.",
    image_url: img("photo-1593073862407-a3ce22748763"),
    price_from_usd: 79,
    duration_min: 420,
    duration_max: 480,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d903-135749P7",
    viator_base_level: "Puerto-Rico",
    category: "culture",
    sort_order: 310,
  },
  {
    slug: "coffee-plantation-hacienda-buena-vista",
    title: "Hacienda Buena Vista Coffee Plantation Tour (Ponce)",
    short_description: "A 19th-century hydraulic coffee mill near Ponce — guided tour with tastings.",
    image_url: img("photo-1447933601403-0c6688de566a"),
    price_from_usd: 85,
    duration_min: 480,
    duration_max: 540,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "culinary",
    sort_order: 311,
  },
  {
    slug: "hacienda-san-pedro-coffee",
    title: "Hacienda San Pedro Coffee Estate Tour — Jayuya",
    short_description: "Award-winning arabica highlands estate — pick, process, and taste specialty coffee.",
    image_url: img("photo-1611854779393-1b2da9d400fe"),
    price_from_usd: 75,
    duration_min: 360,
    duration_max: 420,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "culinary",
    sort_order: 312,
  },
  {
    slug: "san-juan-kitesurfing-lesson",
    title: "Kitesurfing Beginner Lesson — Isla Verde",
    short_description: "Learn to harness the trade winds with a certified IKO instructor on flat water.",
    image_url: img("photo-1527664568748-51369f489a42"),
    price_from_usd: 149,
    duration_min: 180,
    duration_max: 240,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 313,
  },
  {
    slug: "san-juan-helicopter-45min",
    title: "45-Minute Helicopter Tour Across Puerto Rico",
    short_description: "El Yunque, karst hills, Old San Juan, and the south coast — all from the air.",
    image_url: img("photo-1464037866556-6812c9d1c72e"),
    price_from_usd: 349,
    duration_min: 45,
    duration_max: 60,
    type: "multi_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-452098P1",
    viator_base_level: "San-Juan",
    category: "adventure",
    sort_order: 314,
  },
  {
    slug: "boqueron-sunset-kayak",
    title: "Boquerón Sunset Kayak & Mangrove Tour",
    short_description: "Paddle through Cabo Rojo's mangrove channels as the sun sets over the Caribbean.",
    image_url: img("photo-1579332550177-31a901024747"),
    price_from_usd: 65,
    duration_min: 300,
    duration_max: 360,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 315,
  },
  {
    slug: "san-german-day-trip",
    title: "San Germán & Porta Coeli Day Trip from San Juan",
    short_description: "Puerto Rico's second-oldest city — baroque churches, colonial plazas, and mountain air.",
    image_url: img("photo-1499424769867-03de11e2d3c3"),
    price_from_usd: 89,
    duration_min: 540,
    duration_max: 600,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "history",
    sort_order: 316,
  },
  {
    slug: "fajardo-kayak-el-yunque-bio",
    title: "El Yunque + Fajardo Bio Bay Combo (Full-Day + Evening)",
    short_description: "Rainforest waterfalls in the morning, bioluminescent kayaking at night — one epic day.",
    image_url: img("photo-1536441918530-c3bae05caf69"),
    price_from_usd: 145,
    duration_min: 600,
    duration_max: 720,
    type: "multi_day",
    viator_slug: "Laguna-Grande",
    viator_attraction_id: "d23854-a18344",
    viator_base_level: "Fajardo",
    category: "combo",
    sort_order: 317,
  },
  {
    slug: "ponce-walking-small-group",
    title: "Ponce Small-Group Walking Tour",
    short_description: "History Museum, Cathedral of Guadalupe, and Parque de Bombas with a local guide.",
    image_url: img("photo-1589402278102-d3a969a78713"),
    price_from_usd: 55,
    duration_min: 480,
    duration_max: 540,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-102301P2",
    viator_base_level: "Puerto-Rico",
    category: "history",
    sort_order: 318,
  },
  {
    slug: "rio-camuy-cueva-ventana-combo",
    title: "Río Camuy Caves & Cueva Ventana Combo",
    short_description: "Two of Puerto Rico's most dramatic cave systems in one north-coast day trip.",
    image_url: img("photo-1725780632003-894557a203f7"),
    price_from_usd: 119,
    duration_min: 540,
    duration_max: 600,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d903-a2462",
    viator_base_level: "Puerto-Rico",
    category: "nature",
    sort_order: 319,
  },
  {
    slug: "mona-island-day-trip",
    title: "Mona Island Snorkel & Wildlife Day Trip",
    short_description: "\"Galápagos of the Caribbean\" — pristine reefs, iguanas, and zero crowds.",
    image_url: img("photo-1582967788606-a171c1080cb0"),
    price_from_usd: 299,
    duration_min: 720,
    duration_max: 900,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 320,
  },
  {
    slug: "goat-yoga-farm",
    title: "Goat Yoga & Farm Experience — Puerto Rico",
    short_description: "Sunrise yoga on a working farm with baby goats wandering your mat.",
    image_url: img("photo-1516467508483-a7212febe31a"),
    price_from_usd: 55,
    duration_min: 120,
    duration_max: 180,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "wellness",
    sort_order: 321,
  },
  {
    slug: "old-san-juan-food-truck-tour",
    title: "San Juan Food Truck & Street Food Tour",
    short_description: "Six curated stops across Santurce's food-truck scene — chef-led with local stories.",
    image_url: img("photo-1504674900247-0877df9cc836"),
    price_from_usd: 79,
    duration_min: 180,
    duration_max: 240,
    type: "multi_day",
    viator_slug: "Old-San-Juan",
    viator_attraction_id: "d903-a2460",
    viator_base_level: "San-Juan",
    category: "culinary",
    sort_order: 322,
  },
  {
    slug: "catano-bacardi-lookout",
    title: "Cataño Bacardí Lookout & Distillery Combo",
    short_description: "Ferry to Cataño, VIP rum tasting, and rooftop views of Old San Juan bay.",
    image_url: img("photo-1608232385022-8ba61bec6c59"),
    price_from_usd: 79,
    duration_min: 240,
    duration_max: 300,
    type: "multi_day",
    viator_slug: "Bacardi-Rum-Factory",
    viator_attraction_id: "d903-a2454",
    viator_base_level: "San-Juan",
    category: "culinary",
    sort_order: 323,
  },
  {
    slug: "el-yunque-kayak-rainforest",
    title: "El Yunque Rainforest Kayak & Waterfall Swim",
    short_description: "Paddle up the Río Mameyes into El Yunque canopy, then swim at cascading falls.",
    image_url: img("photo-1561271484-3a69b8e31344"),
    price_from_usd: 95,
    duration_min: 420,
    duration_max: 480,
    type: "multi_day",
    viator_slug: "El-Yunque-National-Forest",
    viator_attraction_id: "d903-a2461",
    viator_base_level: "San-Juan",
    category: "adventure",
    sort_order: 324,
  },
  {
    slug: "vieques-atv-beaches",
    title: "Vieques ATV Tour to Secret Beaches",
    short_description: "Hit Vieques' off-road trails to reach secluded shores inaccessible by car.",
    image_url: img("photo-1675428604186-a165487f857c"),
    price_from_usd: 89,
    duration_min: 360,
    duration_max: 480,
    type: "multi_day",
    viator_slug: "Vieques-Island",
    viator_attraction_id: "d36-a19410",
    viator_base_level: "Puerto-Rico",
    category: "adventure",
    sort_order: 325,
  },
  {
    slug: "culebra-snorkel-full-day",
    title: "Culebra Full-Day Snorkel & Luis Peña Reserve",
    short_description: "Blue tang, eagle rays, and hawksbill turtles in the most protected reef in Puerto Rico.",
    image_url: img("photo-1582273417870-183e69b360e7"),
    price_from_usd: 195,
    duration_min: 600,
    duration_max: 720,
    type: "multi_day",
    viator_slug: "Culebra-Island",
    viator_attraction_id: "d36-a19414",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 326,
  },
  {
    slug: "san-juan-surf-lesson",
    title: "Surfing Lesson at Isla Verde / Pine Grove Beach",
    short_description: "Perfect rolling beach breaks for beginners — boards and rash guards included.",
    image_url: img("photo-1531722569936-825d4eaf9af7"),
    price_from_usd: 75,
    duration_min: 120,
    duration_max: 150,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-a19408",
    viator_base_level: "Puerto-Rico",
    category: "water",
    sort_order: 327,
  },
  {
    slug: "hacienda-campo-rico-utv",
    title: "Hacienda Campo Rico UTV Salinas Adventure",
    short_description: "UTV through 2,300 acres of hills, lagoons, and mangroves east of San Juan.",
    image_url: img("photo-1648853070657-6d58398bee93"),
    price_from_usd: 169,
    duration_min: 180,
    duration_max: 240,
    type: "multi_day",
    viator_slug: "Puerto-Rico",
    viator_attraction_id: "d36-5229ATVCR",
    viator_base_level: "Puerto-Rico",
    category: "adventure",
    sort_order: 328,
  },
  {
    slug: "isla-verde-sunset-catamaran",
    title: "Isla Verde Sunset Catamaran & Cocktails",
    short_description: "Two-hour evening sail along the Condado coast with DJ and open bar.",
    image_url: img("photo-1629908513781-1857f7ec2c8a"),
    price_from_usd: 79,
    duration_min: 120,
    duration_max: 150,
    type: "multi_day",
    viator_slug: "San-Juan-Bay",
    viator_attraction_id: "d903-a22255",
    viator_base_level: "San-Juan",
    category: "water",
    sort_order: 329,
  },
  {
    slug: "el-yunque-night-hike",
    title: "El Yunque Night Hike & Tree Frog Tour",
    short_description: "Hear the iconic coquí tree frog chorus and spot bioluminescent fungi after dark.",
    image_url: img("photo-1597627094703-2a8af9caa749"),
    price_from_usd: 85,
    duration_min: 300,
    duration_max: 360,
    type: "multi_day",
    viator_slug: "El-Yunque-National-Forest",
    viator_attraction_id: "d903-a2461",
    viator_base_level: "San-Juan",
    category: "nature",
    sort_order: 330,
  },
];

export async function seedExcursions() {
  const supabase = getServiceRoleSupabase();
  const rows = [...cruiseDay, ...multiDay, ...extraCruiseDay, ...extraMultiDay].map((r) => ({
    ...r,
    is_active: true,
    is_hero: r.is_hero ?? false,
  }));

  // cast to any — stub generated types don't include `excursions` table yet
  const { error } = await (supabase as any)
    .from("excursions")
    .upsert(rows, { onConflict: "slug" });

  if (error) throw error;
  console.log(`  upserted ${rows.length} excursions (${cruiseDay.length + extraCruiseDay.length} cruise_day + ${multiDay.length + extraMultiDay.length} multi_day)`);
}
