// db/seed/excursions.ts
import { getServiceRoleSupabase } from "./_supabase";

type Row = {
  slug: string;
  title: string;
  short_description: string;
  image_url: string;
  price_from_usd: number;
  duration_min: number;
  duration_max?: number;
  type: "cruise_day" | "multi_day" | "both";
  viator_slug: string;
  viator_attraction_id: string;
  viator_base_level: "San-Juan" | "Puerto-Rico" | "Vieques" | "Fajardo";
  category: string;
  is_hero?: boolean;
  sort_order: number;
};

// Image URL helper — picks a stable Unsplash photo for the category.
const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

const cruiseDay: Row[] = [
  { slug: "old-san-juan-walking", title: "Old San Juan Walking Tour", short_description: "Cobblestone streets, UNESCO history, and 500 years of stories.", image_url: img("photo-1591017403286-fd8493524e1d"), price_from_usd: 45, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", is_hero: true, sort_order: 1 },
  { slug: "el-morro-fort-tour", title: "Castillo San Felipe del Morro Tour", short_description: "The 16th-century clifftop Spanish fortress guarding San Juan Bay.", image_url: img("photo-1583499871880-de841d1ace2a"), price_from_usd: 10, duration_min: 120, type: "cruise_day", viator_slug: "Castillo-San-Felipe-del-Morro", viator_attraction_id: "d903-a3885", viator_base_level: "San-Juan", category: "history", is_hero: true, sort_order: 2 },
  { slug: "casa-bacardi-distillery", title: "Casa Bacardí Distillery Tour", short_description: "The world's largest premium rum distillery, with a signature cocktail.", image_url: img("photo-1569529465841-dfecdab7503b"), price_from_usd: 33, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", is_hero: true, sort_order: 3 },
  { slug: "el-yunque-half-day", title: "El Yunque Rainforest Half-Day Tour", short_description: "Tropical rainforest with waterfalls, lookouts, and lush trails.", image_url: img("photo-1518495973542-4542c06a5843"), price_from_usd: 60, duration_min: 240, duration_max: 300, type: "cruise_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "nature", is_hero: true, sort_order: 4 },
  { slug: "flavors-san-juan-food-tour", title: "Flavors of San Juan Food Tour", short_description: "Mofongo, lechón, alcapurrias, and mojito across nine stops.", image_url: img("photo-1504674900247-0877df9cc836"), price_from_usd: 99, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", is_hero: true, sort_order: 5 },
  { slug: "el-morro-cristobal-combo", title: "El Morro + San Cristóbal Combo Walking Tour", short_description: "Both UNESCO forts in a single half-day pass.", image_url: img("photo-1564507592333-c60657eea523"), price_from_usd: 54, duration_min: 180, type: "cruise_day", viator_slug: "Castillo-San-Felipe-del-Morro", viator_attraction_id: "d903-a3885", viator_base_level: "San-Juan", category: "history", sort_order: 6 },
  { slug: "bacardi-mixology-class", title: "Casa Bacardí Rum Mixology Class", short_description: "Hands-on cocktail class with a master mixologist.", image_url: img("photo-1551024601-bec78aea704b"), price_from_usd: 60, duration_min: 120, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", sort_order: 7 },
  { slug: "mofongo-mojito-class", title: "Mofongo & Mojito Cooking Class", short_description: "Pound your own mofongo and muddle your own mojito.", image_url: img("photo-1551183053-bf91a1d81141"), price_from_usd: 89, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 8 },
  { slug: "el-yunque-luquillo", title: "El Yunque + Luquillo Beach Half-Day", short_description: "Hike to a waterfall, then cool off at Luquillo Beach.", image_url: img("photo-1507525428034-b723cf961d3e"), price_from_usd: 50, duration_min: 300, duration_max: 360, type: "cruise_day", viator_slug: "Luquillo-Beach", viator_attraction_id: "d903-a10255", viator_base_level: "San-Juan", category: "nature", sort_order: 9 },
  { slug: "osj-rum-salsa-class", title: "Old San Juan Rum & Salsa Class", short_description: "Two rum cocktails and basic salsa steps in three breezy hours.", image_url: img("photo-1535525153412-5a092d46af8c"), price_from_usd: 79, duration_min: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 10 },
  { slug: "escambron-snorkel", title: "Escambrón Beach Snorkel Tour", short_description: "Protected reef teeming with sea turtles, minutes from the pier.", image_url: img("photo-1582142306909-195724d33f3f"), price_from_usd: 45, duration_min: 120, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "water", sort_order: 11 },
  { slug: "condado-clear-kayak", title: "Clear-Kayak Tour of Condado Lagoon", short_description: "Paddle a see-through kayak across a calm urban lagoon.", image_url: img("photo-1502920917128-1aa500764cbd"), price_from_usd: 65, duration_min: 90, duration_max: 120, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "water", sort_order: 12 },
  { slug: "san-juan-bay-catamaran", title: "San Juan Bay Catamaran Snorkel & Sail", short_description: "Half-day sail with snorkel stop and skyline views.", image_url: img("photo-1473186578172-c141e6798cf4"), price_from_usd: 95, duration_min: 180, duration_max: 240, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 13 },
  { slug: "osj-self-audio-tour", title: "Old San Juan Self-Guided Audio Tour", short_description: "App-based walking tour, perfect for tight cruise schedules.", image_url: img("photo-1601225286059-c5d8da7e9a1d"), price_from_usd: 13, duration_min: 60, duration_max: 180, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", sort_order: 14 },
  { slug: "osj-ghost-walk", title: "Old San Juan Ghost Walk", short_description: "Lantern-lit evening tour through haunted plazas.", image_url: img("photo-1518770660439-4636190af475"), price_from_usd: 35, duration_min: 120, duration_max: 150, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "history", sort_order: 15 },
  { slug: "bacardi-osj-combo", title: "Bacardí + Old San Juan Combo", short_description: "Rum distillery + walking tour in one half day.", image_url: img("photo-1530021232320-687d8e3dba54"), price_from_usd: 89, duration_min: 300, type: "cruise_day", viator_slug: "Bacardi-Rum-Factory", viator_attraction_id: "d903-a2454", viator_base_level: "San-Juan", category: "culinary", sort_order: 16 },
  { slug: "san-juan-harbor-cruise", title: "San Juan Harbor Sightseeing Cruise", short_description: "Narrated 90-minute harbor cruise with El Morro views.", image_url: img("photo-1473445730015-841f29a9490b"), price_from_usd: 35, duration_min: 90, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 17 },
  { slug: "osj-sip-stroll", title: "Old San Juan Sip & Stroll Mojito Tour", short_description: "Three bars, three mojitos, one walking guide.", image_url: img("photo-1551024601-bec78aea704b"), price_from_usd: 69, duration_min: 150, type: "cruise_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "culinary", sort_order: 18 },
  { slug: "osj-sunset-harbor", title: "Old San Juan Sunset Harbor Tour", short_description: "Late-afternoon harbor cruise timed for golden hour.", image_url: img("photo-1495954484750-af469f2f9be5"), price_from_usd: 59, duration_min: 120, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 19 },
  { slug: "san-juan-jet-ski", title: "Jet Ski Tour of San Juan Bay", short_description: "Buzz across the bay with El Morro as your backdrop.", image_url: img("photo-1565017228812-3b9cda4a2884"), price_from_usd: 169, duration_min: 60, duration_max: 120, type: "cruise_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 20 },
];

const multiDay: Row[] = [
  { slug: "vieques-bio-bay-kayak", title: "Vieques Bio Bay (Mosquito Bay) Kayak", short_description: "Every paddle stroke ignites blue plankton beneath your kayak.", image_url: img("photo-1535970793482-07de93762dc4"), price_from_usd: 65, duration_min: 90, duration_max: 120, type: "multi_day", viator_slug: "Bioluminescent-Bay", viator_attraction_id: "d22812-a22596", viator_base_level: "Vieques", category: "water", is_hero: true, sort_order: 101 },
  { slug: "culebra-flamenco-catamaran", title: "Culebra & Flamenco Beach Catamaran Day Trip", short_description: "Snorkel Carlos Rosario reef and beach on world-ranked Flamenco Beach.", image_url: img("photo-1507525428034-b723cf961d3e"), price_from_usd: 185, duration_min: 480, duration_max: 600, type: "multi_day", viator_slug: "Culebra-Island", viator_attraction_id: "d36-a19414", viator_base_level: "Puerto-Rico", category: "water", is_hero: true, sort_order: 102 },
  { slug: "el-yunque-full-day", title: "El Yunque Full-Day Rainforest & Waterfalls", short_description: "La Coca and Juan Diego falls, plus a Luquillo Beach finale.", image_url: img("photo-1518495973542-4542c06a5843"), price_from_usd: 80, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "nature", is_hero: true, sort_order: 103 },
  { slug: "toro-verde-beast", title: "Toro Verde 'The Beast' Zipline", short_description: "Nearly a mile across a mountain valley at 60 mph.", image_url: img("photo-1488554378835-f7acf46e6c98"), price_from_usd: 67, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", is_hero: true, sort_order: 104 },
  { slug: "fajardo-bio-bay-kayak", title: "Fajardo Laguna Grande Bio Bay Kayak", short_description: "The most-accessible bioluminescent lagoon, done from San Juan in one evening.", image_url: img("photo-1505228395891-9a51e7e86bf6"), price_from_usd: 69, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", is_hero: true, sort_order: 105 },
  { slug: "culebra-ferry-turtle", title: "Culebra Island Ferry + Turtle Swim", short_description: "Ferry, sea turtles in Luis Peña Reserve, plus Flamenco Beach.", image_url: img("photo-1582967788606-a171c1080cb0"), price_from_usd: 175, duration_min: 600, duration_max: 720, type: "multi_day", viator_slug: "Flamenco-Beach-Playa-Flamenco", viator_attraction_id: "d903-a15793", viator_base_level: "San-Juan", category: "water", sort_order: 106 },
  { slug: "el-yunque-waterslide", title: "El Yunque Waterslide & Cliff-Jumping", short_description: "Off-the-beaten-path waterfalls with 20-foot cliff jumps.", image_url: img("photo-1428908728789-d2de25dbd4e2"), price_from_usd: 85, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "adventure", sort_order: 107 },
  { slug: "fajardo-catamaran-icacos", title: "Fajardo Catamaran Snorkel & Sunset Sail", short_description: "All-day or sunset catamaran to Icacos and Palomino.", image_url: img("photo-1473186578172-c141e6798cf4"), price_from_usd: 119, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", sort_order: 108 },
  { slug: "toro-verde-monster", title: "Toro Verde 'The Monster' Zipline", short_description: "World's longest zipline — 1.5 miles superman-style.", image_url: img("photo-1517457373958-b7bdd4587205"), price_from_usd: 125, duration_min: 360, duration_max: 420, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", sort_order: 109 },
  { slug: "rio-camuy-caves", title: "Río Camuy Cave Park & Arecibo Day Trip", short_description: "Third-longest underground river system in the world.", image_url: img("photo-1551522435-a13afa10f103"), price_from_usd: 99, duration_min: 480, duration_max: 540, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "nature", sort_order: 110 },
  { slug: "cueva-ventana", title: "Cueva Ventana 'Window Cave' & Waterfall", short_description: "Clifftop cave with a window view over the Río Grande de Arecibo.", image_url: img("photo-1551522435-a13afa10f103"), price_from_usd: 89, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "nature", sort_order: 111 },
  { slug: "charco-azul", title: "Charco Azul Cave, River & Waterfall", short_description: "Arenales caves, turquoise swimming hole, hidden waterfalls.", image_url: img("photo-1428908728789-d2de25dbd4e2"), price_from_usd: 75, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "Rio-Camuy-Cave-Park", viator_attraction_id: "d903-a2462", viator_base_level: "San-Juan", category: "adventure", sort_order: 112 },
  { slug: "hacienda-campo-rico-atv", title: "Hacienda Campo Rico ATV Adventure", short_description: "Drive an ATV across 2,300 acres of mangroves and lookouts.", image_url: img("photo-1533473359331-0135ef1b58bf"), price_from_usd: 149, duration_min: 180, duration_max: 240, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "adventure", sort_order: 113 },
  { slug: "carabali-horseback", title: "Carabalí Rainforest Beach Horseback Ride", short_description: "Paso Fino horses along the Mameyes River and Atlantic beaches.", image_url: img("photo-1553284965-83fd3e82fa5a"), price_from_usd: 95, duration_min: 300, duration_max: 360, type: "multi_day", viator_slug: "El-Yunque-National-Forest", viator_attraction_id: "d903-a2461", viator_base_level: "San-Juan", category: "adventure", sort_order: 114 },
  { slug: "icacos-catamaran-picnic", title: "Icacos Deserted Island Catamaran & Picnic", short_description: "All-day catamaran to a deserted cay with lunch and drinks.", image_url: img("photo-1582967788606-a171c1080cb0"), price_from_usd: 139, duration_min: 420, duration_max: 480, type: "multi_day", viator_slug: "Laguna-Grande", viator_attraction_id: "d23854-a18344", viator_base_level: "Fajardo", category: "water", sort_order: 115 },
  { slug: "la-parguera-bio-bay", title: "La Parguera Bio Bay Boat & Swim", short_description: "PR's only swimmable bio bay — splash through bioluminescent water.", image_url: img("photo-1535970793482-07de93762dc4"), price_from_usd: 55, duration_min: 480, duration_max: 600, type: "multi_day", viator_slug: "Bioluminescent-Bay", viator_attraction_id: "d22812-a22596", viator_base_level: "Vieques", category: "water", sort_order: 116 },
  { slug: "three-in-one-day", title: "Old San Juan, El Yunque & Beach (3-in-1)", short_description: "Old San Juan, El Yunque waterfalls, and Luquillo Beach in one day.", image_url: img("photo-1591017403286-fd8493524e1d"), price_from_usd: 65, duration_min: 480, duration_max: 540, type: "multi_day", viator_slug: "Old-San-Juan", viator_attraction_id: "d903-a2460", viator_base_level: "San-Juan", category: "combo", sort_order: 117 },
  { slug: "vieques-bio-bay-from-sj", title: "Vieques Bio Bay Day Trip from San Juan", short_description: "Same-day round-trip ferry + van combo for the brightest bio bay.", image_url: img("photo-1535970793482-07de93762dc4"), price_from_usd: 230, duration_min: 840, duration_max: 960, type: "multi_day", viator_slug: "Vieques-Island", viator_attraction_id: "d36-a19410", viator_base_level: "Puerto-Rico", category: "water", sort_order: 118 },
  { slug: "rio-grande-loiza-kayak", title: "Río Grande de Loíza Kayak & Mangrove Tour", short_description: "Quiet paddle through Loíza's Afro-Caribbean mangrove estuary.", image_url: img("photo-1502920917128-1aa500764cbd"), price_from_usd: 65, duration_min: 240, duration_max: 300, type: "multi_day", viator_slug: "Luquillo-Beach", viator_attraction_id: "d903-a10255", viator_base_level: "San-Juan", category: "water", sort_order: 119 },
  { slug: "bacardi-sunset-sail", title: "Bacardí Historic Sunset Boat Tour", short_description: "Romantic evening sail with cocktails timed to sunset over El Morro.", image_url: img("photo-1495954484750-af469f2f9be5"), price_from_usd: 89, duration_min: 120, type: "multi_day", viator_slug: "San-Juan-Bay", viator_attraction_id: "d903-a22255", viator_base_level: "San-Juan", category: "water", sort_order: 120 },
];

export async function seedExcursions() {
  const supabase = getServiceRoleSupabase();
  const rows = [...cruiseDay, ...multiDay].map((r) => ({
    ...r,
    is_active: true,
    is_hero: r.is_hero ?? false,
  }));

  // cast to any — stub generated types don't include `excursions` table yet
  const { error } = await (supabase as any)
    .from("excursions")
    .upsert(rows, { onConflict: "slug" });

  if (error) throw error;
  console.log(`  upserted ${rows.length} excursions (${cruiseDay.length} cruise_day + ${multiDay.length} multi_day)`);
}
