// db/seed/masterminds.ts
import { getServiceRoleSupabase } from "@/lib/supabase/admin";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

const rows = [
  { slug: "2022-act-society", title: "The 20/22 Act Society", one_line: "Flagship community for Act 60 decree holders and prospective relocators.", image_url: img("photo-1556761175-5973dc0f32e7"), destination_url: "https://www.the2022actsociety.org/", tier: "paid_t1" as const, location: "Dorado", verified: true, sort_order: 1 },
  { slug: "eo-puerto-rico", title: "EO Puerto Rico", one_line: "Local chapter of Entrepreneurs' Organization — founders of $1M+ businesses.", image_url: img("photo-1556761175-b413da4baf72"), destination_url: "https://eopuertorico.org/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 2 },
  { slug: "ypo-puerto-rico", title: "YPO Puerto Rico", one_line: "Young Presidents' Organization chapter for CEOs of significant companies.", image_url: img("photo-1559136555-9303baea8ebd"), destination_url: "https://www.ypo.org/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 3 },
  { slug: "gobundance-pr", title: "GoBundance (PR Members)", one_line: "National peer mastermind for high-net-worth men — strong PR member base.", image_url: img("photo-1542744173-8e7e53415bb0"), destination_url: "https://gobundance.com/", tier: "paid_t1" as const, location: "Island-wide", verified: false, sort_order: 4 },
  { slug: "uncorrelated-pr", title: "Uncorrelated Alts PR", one_line: "Annual investor conference bringing 400+ family offices and Act 60 entrepreneurs together.", image_url: img("photo-1554224155-6726b3ff858f"), destination_url: "https://uncorrelatedpr.com/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 5 },
  { slug: "prbta", title: "PR Blockchain Trade Association", one_line: "De facto Web3 trade org — hosts PR Blockchain Week and workshops.", image_url: img("photo-1639762681485-074b7f938ba0"), destination_url: "https://www.prblockchain.org/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 6 },
  { slug: "cryptomondays", title: "CryptoMondays San Juan", one_line: "Weekly Web3 meetup at Poet's Passage in Old San Juan.", image_url: img("photo-1639762681485-074b7f938ba0"), destination_url: "https://www.facebook.com/CryptoMondaysSanJuan/", tier: "paid_t1" as const, location: "Old San Juan", verified: true, sort_order: 7 },
  { slug: "bitangels", title: "BitAngels San Juan", one_line: "Local node of the global blockchain angel investor network.", image_url: img("photo-1605792657660-596af9009e82"), destination_url: "https://bitangels.network/san-juan", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 8 },
  { slug: "parallel18", title: "Parallel18", one_line: "Government-backed accelerator running international and pre-acceleration programs.", image_url: img("photo-1556761175-5973dc0f32e7"), destination_url: "https://parallel18.com/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 9 },
  { slug: "grupo-guayacan", title: "Grupo Guayacán", one_line: "Nonprofit running EnterPRize competition and I-Corps PR — 2,500+ entrepreneurs served.", image_url: img("photo-1531482615713-2afd69097998"), destination_url: "https://guayacan.org/", tier: "paid_t1" as const, location: "San Juan", verified: true, sort_order: 10 },
  { slug: "piloto-151", title: "Piloto 151", one_line: "Puerto Rico's first coworking space — community hub in Old San Juan and Dorado.", image_url: img("photo-1497366216548-37526070297c"), destination_url: "https://piloto151.com/", tier: "paid_t1" as const, location: "OSJ + Dorado", verified: true, sort_order: 11 },
  { slug: "colmena66", title: "Colmena66", one_line: "Resource connector linking founders to 250+ ecosystem orgs across the island.", image_url: img("photo-1521737711867-e3b97375f902"), destination_url: "https://www.colmena66.com/", tier: "paid_t1" as const, location: "Island-wide", verified: true, sort_order: 12 },
  { slug: "indie-hackers-pr", title: "Indie Hackers Puerto Rico", one_line: "Local IH meetup for bootstrappers, solopreneurs, and digital nomads.", image_url: img("photo-1522071820081-009f0129c71c"), destination_url: "https://www.indiehackerspr.com/", tier: "local_t2" as const, location: "San Juan", verified: true, sort_order: 13 },
  { slug: "aa-san-juan", title: "AA San Juan / Caribbean 12 Step", one_line: "Daily English-language AA meetings in Condado; includes LGBTQIA+ tracks.", image_url: img("photo-1499209974431-9dddcece7f88"), destination_url: "https://www.aasanjuan.org/", tier: "local_t2" as const, location: "Condado", verified: true, sort_order: 14 },
  { slug: "la-academia-bjj", title: "La Academia Jiu Jitsu", one_line: "Premier BJJ academy in Santurce — community hub for expats and locals.", image_url: img("photo-1555597673-b21d5c935865"), destination_url: "https://la-academia.com/", tier: "local_t2" as const, location: "Santurce", verified: true, sort_order: 15 },
  { slug: "opex-san-juan", title: "OPEX San Juan", one_line: "CrossFit + personalized strength training with a tight regular-member community.", image_url: img("photo-1534438327276-14e5300c3a48"), destination_url: "https://www.opexsj.com/", tier: "local_t2" as const, location: "San Juan", verified: true, sort_order: 16 },
  { slug: "run-club-san-juan", title: "San Juan Run Club", one_line: "Casual social run group meeting weekly in Condado.", image_url: img("photo-1452626038306-9aae5e071dd3"), destination_url: "https://www.instagram.com/sanjuanrunclub/", tier: "local_t2" as const, location: "Condado", verified: true, sort_order: 17 },
  { slug: "union-church-sj", title: "Union Church of San Juan", one_line: "English-speaking interdenominational church frequented by expats and Act 60 families.", image_url: img("photo-1438032005730-c779502df39b"), destination_url: "https://www.unionchurchsj.org/", tier: "local_t2" as const, location: "San Juan", verified: true, sort_order: 18 },
  { slug: "rincon-surf", title: "Rincón Surf School (Community Hub)", one_line: "Densest expat-surfer overlap on the island; west-coast surf culture's beating heart.", image_url: img("photo-1502680390469-be75c86b636f"), destination_url: "https://www.rinconsurfschool.com/", tier: "local_t2" as const, location: "Rincón", verified: true, sort_order: 19 },
  { slug: "metro-wbc", title: "Metro Women's Business Center", one_line: "SBA-backed women's entrepreneurship center with bilingual free programming.", image_url: img("photo-1573164713988-8665fc963095"), destination_url: "https://puertoricowomen.org/", tier: "local_t2" as const, location: "San Juan / Bayamón", verified: true, sort_order: 20 },
];

export async function seedMasterminds() {
  const supabase = getServiceRoleSupabase();
  const data = rows.map((r) => ({ ...r, is_active: true }));
  const { error } = await (supabase as any).from("masterminds").upsert(data, { onConflict: "slug" });
  if (error) throw error;
  console.log(`  upserted ${rows.length} masterminds (12 paid_t1 + 8 local_t2)`);
}
